name: pmsn20232
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  concentric_transition: ^1.0.3
  flutter_slider_drawer: ^2.1.3
  http: ^0.13.6
  day_night_switcher: ^0.2.0+1
  shared_preferences: ^2.2.2
  sqflite: ^2.2.8
  path_provider: ^2.1.1
  lottie: ^2.3.2
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  carousel_pro: ^1.0.0
  flappy_search_bar: ^1.7.2
  provider: ^6.0.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/.
    - assets/animation/.
    - assets/
